lw_louvre_homepage:
    path:     /
    defaults: { _controller: LWLouvreBundle:Louvre:index }

lw_louvre_billeterie:
    path:     /billeterie
    defaults: { _controller: LWLouvreBundle:Louvre:billeterie }

lw_louvre_stripe_pay:
    path:     /stripe_pay
    defaults: { _controller: LWLouvreBundle:Louvre:stripe_pay }

