lw_louvre_homepage:
    path:     /
    defaults: { _controller: LWLouvreBundle:Louvre:index }

lw_louvre_billeterie:
    path:     /billeterie
    defaults: { _controller: LWLouvreBundle:Louvre:billeterie }

lw_louvre_stripe_form:
    path:     /stripeForm
    defaults: { _controller: LWLouvreBundle:Louvre:stripeForm }
lw_louvre_stripe_payment:
    path:     /stripePayment
    defaults: { _controller: LWLouvreBundle:Louvre:stripePayment }

lw_louvre_avaible_date:
    path:     /avaible_date
    defaults: { _controller: LWLouvreBundle:Louvre:avaibleDate }

